# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/cespare/xxhash";
    fetch = {
      type = "git";
      url = "https://github.com/cespare/xxhash";
      rev = "32f3a100fff237d14029d34ec8579ef02aaaf87c";
      sha256 = "0pd81gm5bzf9z0shypmfp3jb06fv8m072154a5n1bwq3lcpf9qx1";
    };
  }
  {
    goPackagePath = "github.com/fatih/color";
    fetch = {
      type = "git";
      url = "https://github.com/fatih/color";
      rev = "3f9d52f7176a6927daacff70a3e8d1dc2025c53e";
      sha256 = "165ww24x6ba47ji4j14mp3f006ksnmi53ws9280pgd2zcw91nbn8";
    };
  }
  {
    goPackagePath = "github.com/spf13/cobra";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/cobra";
      rev = "f2b07da1e2c38d5f12845a4f607e2e1018cbb1f5";
      sha256 = "0z4x8js65mhwg1gf6sa865pdxfgn45c3av9xlcc1l3xjvcnx32v2";
    };
  }
  {
    goPackagePath = "github.com/spf13/pflag";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/pflag";
      rev = "24fa6976df40757dce6aea913e7b81ade90530e1";
      sha256 = "0rf6prz6gl0l1b3wijzdgq887cdwigvzxvz6gqbm5l8pkq3fx1m9";
    };
  }
]
