# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "zfs-remote-keyloader-${version}";
  version = "2019-02-16";
  rev = "cd39e9685544343e184c609ae775ce6ac2f8b219";

  goPackagePath = "github.com/samhug/zfs-remote-keyloader";

  buildInputs = [ stdenv.glibc.static ];
  CGO_ENABLED=0;
  buildFlags = "-ldflags -s -ldflags -w -ldflags -linkmode=external -ldflags -extldflags=-static";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/samhug/zfs-remote-keyloader.git";
    sha256 = "0zj33ds7qn1z508y6lfsmicl9kv0v216m4vsr267lwmkargn88cn";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
