# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "zfs-remote-keyloader-${version}";
  version = "2019-02-15";
  rev = "6bedb587bb8728f766f0b4c82e6e349c5b3c09df";

  goPackagePath = "github.com/samhug/zfs-remote-keyloader";

  buildInputs = [ stdenv.glibc.static ];
  CGO_ENABLED=0;
  buildFlags = "-ldflags -s -ldflags -w -ldflags -linkmode=external -ldflags -extldflags=-static";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/samhug/zfs-remote-keyloader.git";
    sha256 = "0wllcg6470mxb54s0pwbyj2bwv3cl58z7b375dvzxihpilfggvhr";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
