# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit }:

buildGoPackage rec {
  name = "etlcmd-unstable-${version}";
  version = "2018-12-11";
  rev = "b8525739a933d41bf768a27ca6bedbf4fd34e086";

  goPackagePath = "github.com/samuelhug/etlcmd";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/samuelhug/etlcmd.git";
    sha256 = "1m656b5a644p8id2zzpsdmhwsx90bw9p4z1pdpp2ngz9vfp9d4iw";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
