# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit }:

buildGoPackage rec {
  name = "etlcmd-${version}";
  version = "0.3.4";
  rev = "v${version}";

  goPackagePath = "github.com/samhug/etlcmd";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/samhug/etlcmd.git";
    sha256 = "1x8vdr8vcwsgpnk1jn5kg48r9ww2lnwll2wnq5a8jvixya4n23qy";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
