# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit }:

buildGoPackage rec {
  name = "etlcmd-${version}";
  version = "0.3.5";
  rev = "v${version}";

  goPackagePath = "github.com/samhug/etlcmd";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/samhug/etlcmd.git";
    sha256 = "0vjwy06g7l0i7wqi2059x546gwigxa8c5i7dnclmq2pmlk85z6f5";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {};
}
