# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/aws/aws-sdk-go";
    fetch = {
      type = "git";
      url = "https://github.com/aws/aws-sdk-go";
      rev = "96b0e0eec3a2fc9b6c60552694b8dd9b5e8e1bb0";
      sha256 = "13r3qxq6zwh5pv67cv8phrm88h548aag11dj9jvbgrf9lm73k2lh";
    };
  }
  {
    goPackagePath = "github.com/codegangsta/cli";
    fetch = {
      type = "git";
      url = "https://github.com/codegangsta/cli";
      rev = "693af58b4d51b8fcc7f9d89576da170765980581";
      sha256 = "1krq752xgy658an1696vf4dc2zmp541clwjinhn11394sx2qksh6";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/errwrap";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/errwrap";
      rev = "8a6fb523712970c966eefc6b39ed2c5e74880354";
      sha256 = "0slfb6w3b61xz04r32bi0a1bygc82rjzhqkxj2si2074wynqnr1c";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/go-multierror";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/go-multierror";
      rev = "886a7fbe3eb1c874d46f623bfa70af45f425b3d1";
      sha256 = "00nyn8llqzbfm8aflr9kwsvpzi4kv8v45c141v88xskxp5xf6z49";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/go-uuid";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/go-uuid";
      rev = "4f571afc59f3043a65f8fe6bf46d887b10a01d43";
      sha256 = "0jvb88m0rq41bwgirsadgw7mnayl27av3gd2vqa3xvxp3fy0hp5k";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/hcl";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/hcl";
      rev = "cf7d376da96d9cecec7c7483cec2735efe54a410";
      sha256 = "0i1zhgpyvvgwkz74k8wd3sygsap1saqv37rw0j5vdpaazmpr1qkb";
    };
  }
  {
    goPackagePath = "github.com/jlaffaye/ftp";
    fetch = {
      type = "git";
      url = "https://github.com/jlaffaye/ftp";
      rev = "9284a88df536a8e9d80846c718efeeda5e56b898";
      sha256 = "1z22q8s13frj9msr73qwkkkkmif92jlr4kwdr7ipfhrkazxj2p0j";
    };
  }
  {
    goPackagePath = "github.com/kisielk/sqlstruct";
    fetch = {
      type = "git";
      url = "https://github.com/kisielk/sqlstruct";
      rev = "648daed35d49dac24a4bff253b190a80da3ab6a5";
      sha256 = "0a5ngf6p346iam23y2s3bc5q383877bv7dl7i94p4h5aw2cvjiv1";
    };
  }
  {
    goPackagePath = "github.com/kr/fs";
    fetch = {
      type = "git";
      url = "https://github.com/kr/fs";
      rev = "1455def202f6e05b95cc7bfc7e8ae67ae5141eba";
      sha256 = "11zg176x9hr9q7fsk95r6q0wf214gg4czy02slax4x56n79g6a7q";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-runewidth";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-runewidth";
      rev = "703b5e6b11ae25aeb2af9ebb5d5fdf8fa2575211";
      sha256 = "0znpyz71gajx3g0j2zp63nhjj2c07g16885vxv4ykwnrfmzbgk4w";
    };
  }
  {
    goPackagePath = "github.com/mitchellh/mapstructure";
    fetch = {
      type = "git";
      url = "https://github.com/mitchellh/mapstructure";
      rev = "3536a929edddb9a5b34bd6861dc4a9647cb459fe";
      sha256 = "03bpv28jz9zhn4947saqwi328ydj7f6g6pf1m2d4m5zdh5jlfkrr";
    };
  }
  {
    goPackagePath = "github.com/pkg/errors";
    fetch = {
      type = "git";
      url = "https://github.com/pkg/errors";
      rev = "27936f6d90f9c8e1145f11ed52ffffbfdb9e0af7";
      sha256 = "0yzmgi6g4ak4q8y7w6x0n5cbinlcn8yc3gwgzy4yck00qdn25d6y";
    };
  }
  {
    goPackagePath = "github.com/pkg/sftp";
    fetch = {
      type = "git";
      url = "https://github.com/pkg/sftp";
      rev = "79ae07e7783e194ec8f46029774d8c4966a79ff4";
      sha256 = "0xhxb349wclkazxngmvsas7g0d4j1b5vk8hgrrwyri2jm3c1q56v";
    };
  }
  {
    goPackagePath = "github.com/rhansen2/ratchet";
    fetch = {
      type = "git";
      url = "https://github.com/rhansen2/ratchet";
      rev = "80b37c79f671a29962d9611f4288482451137e4a";
      sha256 = "1jszsj2mj2x9gjz77ays18w8zm2sa1vcz63p673x03sdgk69wxzk";
    };
  }
  {
    goPackagePath = "github.com/robertkrimen/otto";
    fetch = {
      type = "git";
      url = "https://github.com/robertkrimen/otto";
      rev = "15f95af6e78dcd2030d8195a138bd88d4f403546";
      sha256 = "07j7l340lmqwpfscwyb8llk3k37flvs20a4a8vzc85f16xyd9npf";
    };
  }
  {
    goPackagePath = "github.com/samhug/ratchet_processors";
    fetch = {
      type = "git";
      url = "https://github.com/samhug/ratchet_processors";
      rev = "886c2b3c1c60e49a695398adc66d84862b6fde40";
      sha256 = "0grranfk6k152dmcqws72cyir5p1cawfzw7bykfcdhn8zh0i078i";
    };
  }
  {
    goPackagePath = "github.com/samhug/udt";
    fetch = {
      type = "git";
      url = "https://github.com/samhug/udt";
      rev = "5fcba646d462a8d0e0c89dc37efb24d6f658984f";
      sha256 = "101z8frfdkcvsk9sz9pvsigkfsx4k6088jxi2hvbcf118mxk5zj3";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "5c40567a22f818bd14a1ea7245dad9f8ef0691aa";
      sha256 = "17g8fb9vy2sqq8vgz8jdvf6c6d2290gm2qs0i4yzsd86mgn4dlrg";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "b47fdc937951267e2d980171881317deea47f29b";
      sha256 = "17k4qwql2zizrxwjd0qv0gccwgyyv2axiha1vh5lrjfps1h5kli7";
    };
  }
  {
    goPackagePath = "gopkg.in/cheggaaa/pb.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/cheggaaa/pb.v1";
      rev = "f907f6f5dd81f77c2bbc1cde92e4c5a04720cb11";
      sha256 = "13a66cqbpdif804qj12z9ad8r24va9q41gfk71qbc4zg1wsxs3rh";
    };
  }
  {
    goPackagePath = "gopkg.in/sourcemap.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/sourcemap.v1";
      rev = "6e83acea0053641eff084973fee085f0c193c61a";
      sha256 = "08rf2dl13hbnm3fq2cm0nnsspy9fhf922ln23cz5463cv7h62as4";
    };
  }
]
