# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/aws/aws-sdk-go";
    fetch = {
      type = "git";
      url = "https://github.com/aws/aws-sdk-go";
      rev = "8234000fff968de811646c75b200b0c713f800ec";
      sha256 = "09hpdbc9pk0vd5kwrgh2fb5wyb790jw5xa6dfl6iv4ynnwyk5sgg";
    };
  }
  {
    goPackagePath = "github.com/codegangsta/cli";
    fetch = {
      type = "git";
      url = "https://github.com/codegangsta/cli";
      rev = "b67dcf995b6a7b7f14fad5fcb7cc5441b05e814b";
      sha256 = "0n5vq4nydlhb7w12jiwphvxqdy4jwpxc3zwlxyhf05lq1nxfb56h";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/errwrap";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/errwrap";
      rev = "8a6fb523712970c966eefc6b39ed2c5e74880354";
      sha256 = "0slfb6w3b61xz04r32bi0a1bygc82rjzhqkxj2si2074wynqnr1c";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/go-multierror";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/go-multierror";
      rev = "886a7fbe3eb1c874d46f623bfa70af45f425b3d1";
      sha256 = "00nyn8llqzbfm8aflr9kwsvpzi4kv8v45c141v88xskxp5xf6z49";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/go-uuid";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/go-uuid";
      rev = "4f571afc59f3043a65f8fe6bf46d887b10a01d43";
      sha256 = "0jvb88m0rq41bwgirsadgw7mnayl27av3gd2vqa3xvxp3fy0hp5k";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/hcl";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/hcl";
      rev = "65a6292f0157eff210d03ed1bf6c59b190b8b906";
      sha256 = "00qgmygfa4vgf9v3lpz4vp1ca1hcfcxnjqjrvp6z4jjklc8x4mqf";
    };
  }
  {
    goPackagePath = "github.com/jlaffaye/ftp";
    fetch = {
      type = "git";
      url = "https://github.com/jlaffaye/ftp";
      rev = "47f21d10f0ee0d0921769ca3618072e53c12c5a3";
      sha256 = "1kxwh6w3l7hdwx3z19m2fy8fqvcvnl52r4g5vc8g5359n7f6vcrj";
    };
  }
  {
    goPackagePath = "github.com/kisielk/sqlstruct";
    fetch = {
      type = "git";
      url = "https://github.com/kisielk/sqlstruct";
      rev = "648daed35d49dac24a4bff253b190a80da3ab6a5";
      sha256 = "0a5ngf6p346iam23y2s3bc5q383877bv7dl7i94p4h5aw2cvjiv1";
    };
  }
  {
    goPackagePath = "github.com/kr/fs";
    fetch = {
      type = "git";
      url = "https://github.com/kr/fs";
      rev = "1455def202f6e05b95cc7bfc7e8ae67ae5141eba";
      sha256 = "11zg176x9hr9q7fsk95r6q0wf214gg4czy02slax4x56n79g6a7q";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-runewidth";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-runewidth";
      rev = "703b5e6b11ae25aeb2af9ebb5d5fdf8fa2575211";
      sha256 = "0znpyz71gajx3g0j2zp63nhjj2c07g16885vxv4ykwnrfmzbgk4w";
    };
  }
  {
    goPackagePath = "github.com/mitchellh/mapstructure";
    fetch = {
      type = "git";
      url = "https://github.com/mitchellh/mapstructure";
      rev = "3536a929edddb9a5b34bd6861dc4a9647cb459fe";
      sha256 = "03bpv28jz9zhn4947saqwi328ydj7f6g6pf1m2d4m5zdh5jlfkrr";
    };
  }
  {
    goPackagePath = "github.com/pkg/errors";
    fetch = {
      type = "git";
      url = "https://github.com/pkg/errors";
      rev = "059132a15dd08d6704c67711dae0cf35ab991756";
      sha256 = "0bxkbh2rq40kdk8i05am5np77cnskx3571v2k300j5mmj1rl1ijg";
    };
  }
  {
    goPackagePath = "github.com/pkg/sftp";
    fetch = {
      type = "git";
      url = "https://github.com/pkg/sftp";
      rev = "08de04f133f27844173471167014e1a753655ac8";
      sha256 = "090q4xmjbllwl3rpj1hzp0iw3qw1yvp6r3kf5cgw44ai57z96271";
    };
  }
  {
    goPackagePath = "github.com/rhansen2/ratchet";
    fetch = {
      type = "git";
      url = "https://github.com/rhansen2/ratchet";
      rev = "80b37c79f671a29962d9611f4288482451137e4a";
      sha256 = "1jszsj2mj2x9gjz77ays18w8zm2sa1vcz63p673x03sdgk69wxzk";
    };
  }
  {
    goPackagePath = "github.com/robertkrimen/otto";
    fetch = {
      type = "git";
      url = "https://github.com/robertkrimen/otto";
      rev = "15f95af6e78dcd2030d8195a138bd88d4f403546";
      sha256 = "07j7l340lmqwpfscwyb8llk3k37flvs20a4a8vzc85f16xyd9npf";
    };
  }
  {
    goPackagePath = "github.com/samuelhug/ratchet_processors";
    fetch = {
      type = "git";
      url = "https://github.com/samuelhug/ratchet_processors";
      rev = "c2b113e0aba49f7b1e3999ee5f7d4aa36c1a2c27";
      sha256 = "1fhs53f5cvjg3gss8vzs9mm96sasr18q3s8vnwqpkmnabhjlb9wk";
    };
  }
  {
    goPackagePath = "github.com/samuelhug/udt";
    fetch = {
      type = "git";
      url = "https://github.com/samuelhug/udt";
      rev = "69ea6cae38bf54b19622e2a138f93136b872caf0";
      sha256 = "1fym9s40nazf04z9smvdy0ahq6qvch05r66b8f2q22l3ibgrxfvj";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "505ab145d0a99da450461ae2c1a9f6cd10d1f447";
      sha256 = "1vbsvcvmjz6c00p5vf8ls533p52fx2y3gy6v4k5qrdlzl4wf0i5s";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "9a3f9b0469bbc6b8802087ae5c0af9f61502de01";
      sha256 = "04h520vqp6648njhfrpb45p01dkfi2y980yplf60hr95qfnccsbf";
    };
  }
  {
    goPackagePath = "gopkg.in/cheggaaa/pb.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/cheggaaa/pb.v1";
      rev = "1cc5bbe20449079337944d56292c7383510c534c";
      sha256 = "1f995nsqgi0r4qc16nmxlbdxc536hkfwa5k9xb8ypz8d6jlkihag";
    };
  }
  {
    goPackagePath = "gopkg.in/sourcemap.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/sourcemap.v1";
      rev = "6e83acea0053641eff084973fee085f0c193c61a";
      sha256 = "08rf2dl13hbnm3fq2cm0nnsspy9fhf922ln23cz5463cv7h62as4";
    };
  }
]
