# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/aws/aws-sdk-go";
    fetch = {
      type = "git";
      url = "https://github.com/aws/aws-sdk-go";
      rev = "0943d6551d19b0eeee0b3f342659b5f4e871f025";
      sha256 = "1pd8c4b6ywj2nsl7gv3ivxfx31bd1fv87lw75lclzv6283h3jxya";
    };
  }
  {
    goPackagePath = "github.com/codegangsta/cli";
    fetch = {
      type = "git";
      url = "https://github.com/codegangsta/cli";
      rev = "b67dcf995b6a7b7f14fad5fcb7cc5441b05e814b";
      sha256 = "0n5vq4nydlhb7w12jiwphvxqdy4jwpxc3zwlxyhf05lq1nxfb56h";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/errwrap";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/errwrap";
      rev = "8a6fb523712970c966eefc6b39ed2c5e74880354";
      sha256 = "0slfb6w3b61xz04r32bi0a1bygc82rjzhqkxj2si2074wynqnr1c";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/go-multierror";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/go-multierror";
      rev = "886a7fbe3eb1c874d46f623bfa70af45f425b3d1";
      sha256 = "00nyn8llqzbfm8aflr9kwsvpzi4kv8v45c141v88xskxp5xf6z49";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/go-uuid";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/go-uuid";
      rev = "4f571afc59f3043a65f8fe6bf46d887b10a01d43";
      sha256 = "0jvb88m0rq41bwgirsadgw7mnayl27av3gd2vqa3xvxp3fy0hp5k";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/hcl";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/hcl";
      rev = "65a6292f0157eff210d03ed1bf6c59b190b8b906";
      sha256 = "00qgmygfa4vgf9v3lpz4vp1ca1hcfcxnjqjrvp6z4jjklc8x4mqf";
    };
  }
  {
    goPackagePath = "github.com/jlaffaye/ftp";
    fetch = {
      type = "git";
      url = "https://github.com/jlaffaye/ftp";
      rev = "8019e6774408f0ef24753bccba660ae36ff4038d";
      sha256 = "0kc2izxazcgqrqbsqliwcwczvc5iciakblsnk7pj7mmkzzrxjc3w";
    };
  }
  {
    goPackagePath = "github.com/kisielk/sqlstruct";
    fetch = {
      type = "git";
      url = "https://github.com/kisielk/sqlstruct";
      rev = "648daed35d49dac24a4bff253b190a80da3ab6a5";
      sha256 = "0a5ngf6p346iam23y2s3bc5q383877bv7dl7i94p4h5aw2cvjiv1";
    };
  }
  {
    goPackagePath = "github.com/kr/fs";
    fetch = {
      type = "git";
      url = "https://github.com/kr/fs";
      rev = "1455def202f6e05b95cc7bfc7e8ae67ae5141eba";
      sha256 = "11zg176x9hr9q7fsk95r6q0wf214gg4czy02slax4x56n79g6a7q";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-runewidth";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-runewidth";
      rev = "703b5e6b11ae25aeb2af9ebb5d5fdf8fa2575211";
      sha256 = "0znpyz71gajx3g0j2zp63nhjj2c07g16885vxv4ykwnrfmzbgk4w";
    };
  }
  {
    goPackagePath = "github.com/mitchellh/mapstructure";
    fetch = {
      type = "git";
      url = "https://github.com/mitchellh/mapstructure";
      rev = "3536a929edddb9a5b34bd6861dc4a9647cb459fe";
      sha256 = "03bpv28jz9zhn4947saqwi328ydj7f6g6pf1m2d4m5zdh5jlfkrr";
    };
  }
  {
    goPackagePath = "github.com/pkg/errors";
    fetch = {
      type = "git";
      url = "https://github.com/pkg/errors";
      rev = "ffb6e22f01932bf7ac35e0bad9be11f01d1c8685";
      sha256 = "197j5vpv03131rflygl7ks9bqbsx0sydq4bykw2hq0p6kg3grqzz";
    };
  }
  {
    goPackagePath = "github.com/pkg/sftp";
    fetch = {
      type = "git";
      url = "https://github.com/pkg/sftp";
      rev = "a741a7f1d5229e82ed07b9ff00167a2e990bea71";
      sha256 = "1xhs449rjhkwvw0417vc7aq1iv0xx4hsq3l7kqd9zp4plhi3667v";
    };
  }
  {
    goPackagePath = "github.com/rhansen2/ratchet";
    fetch = {
      type = "git";
      url = "https://github.com/rhansen2/ratchet";
      rev = "80b37c79f671a29962d9611f4288482451137e4a";
      sha256 = "1jszsj2mj2x9gjz77ays18w8zm2sa1vcz63p673x03sdgk69wxzk";
    };
  }
  {
    goPackagePath = "github.com/robertkrimen/otto";
    fetch = {
      type = "git";
      url = "https://github.com/robertkrimen/otto";
      rev = "15f95af6e78dcd2030d8195a138bd88d4f403546";
      sha256 = "07j7l340lmqwpfscwyb8llk3k37flvs20a4a8vzc85f16xyd9npf";
    };
  }
  {
    goPackagePath = "github.com/samhug/ratchet_processors";
    fetch = {
      type = "git";
      url = "https://github.com/samhug/ratchet_processors";
      rev = "886c2b3c1c60e49a695398adc66d84862b6fde40";
      sha256 = "0grranfk6k152dmcqws72cyir5p1cawfzw7bykfcdhn8zh0i078i";
    };
  }
  {
    goPackagePath = "github.com/samhug/udt";
    fetch = {
      type = "git";
      url = "https://github.com/samhug/udt";
      rev = "535c43de6aa5f7e955c5c5694b1548314641dac7";
      sha256 = "0ssp1pawvajlgnsib8w70bsmkpzf66gx2lm8w9r12l3y5g9h450n";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "b01c7a72566457eb1420261cdafef86638fc3861";
      sha256 = "0snjjwlzsiakzs43pr4gv5wih5xgh9s2kwaq7gq208330fvqnpfk";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "aca44879d5644da7c5b8ec6a1115e9b6ea6c40d9";
      sha256 = "106vs2md02h16rwnk9mq2h4ix7iyv2n6bfm7v9zp0kknswlag1x0";
    };
  }
  {
    goPackagePath = "gopkg.in/cheggaaa/pb.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/cheggaaa/pb.v1";
      rev = "1cc5bbe20449079337944d56292c7383510c534c";
      sha256 = "1f995nsqgi0r4qc16nmxlbdxc536hkfwa5k9xb8ypz8d6jlkihag";
    };
  }
  {
    goPackagePath = "gopkg.in/sourcemap.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/sourcemap.v1";
      rev = "6e83acea0053641eff084973fee085f0c193c61a";
      sha256 = "08rf2dl13hbnm3fq2cm0nnsspy9fhf922ln23cz5463cv7h62as4";
    };
  }
]
